name: svg_provider
description: SVG Validation and Image Provider
homepage: https://www.dartfoundry.com
repository: https://github.com/dartfoundry/svg_provider
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  http: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ">=3.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
